- hosts: workers
  become: yes
  gather_facts: yes

  tasks:
   - name: Get the token and hash from the master node
     become: yes
     shell: kubeadm token create --print-join-command | awk '{print $5 " " $6}'
     register: join_command

   - name: Copy join command from Ansible host to the worker nodes.
     become: yes
     copy:
       content: "{{ join_command.stdout }}"
       dest: /tmp/kubernetes_join_command
       mode: 0777

   - name: Join the worker nodes to the Kubernetes cluster.
     become: yes
     command: sh /tmp/kubernetes_join_command --ignore-preflight-errors=all
     register: joined_or_not
